FileVersion = 1
Dependencies = {corlib = "*", JSON_Beef = "*"}

[Project]
Name = "JSON_Beef_Test"
StartupObject = "JSON_Beef_Test.Program"

[Configs.Debug.Win64]
PostBuildCmds = ["Execute(\"powershell.exe -Command Copy-Item -Recurse -Force $(ProjectDir)/json $(TargetDir)/test\")"]
